---
# Source: kafka-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-operator-deployment
  labels:
    helm.sh/chart: kafka-operator-0.6.0-nightly
    app.kubernetes.io/name: kafka-operator
    app.kubernetes.io/instance: kafka-operator
    app.kubernetes.io/version: "0.6.0-nightly"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-operator
      app.kubernetes.io/instance: kafka-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-operator
        app.kubernetes.io/instance: kafka-operator
    spec:
      serviceAccountName: kafka-operator-serviceaccount
      securityContext:
        {}
      containers:
        - name: kafka-operator
          securityContext:
            {}
          image: "docker.stackable.tech/stackable/kafka-operator:0.6.0-nightly"
          imagePullPolicy: IfNotPresent
          resources:
            {}
          volumeMounts:
            - mountPath: /etc/stackable/kafka-operator/config-spec
              name: config-spec
          env:
            - name: KAFKA_BROKER_CLUSTERROLE
              value: kafka-operator-kafka-broker-clusterrole
      volumes:
        - name: config-spec
          configMap:
            name: kafka-operator-configmap
