---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  version: 3.8.0-stackable0.8.0
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 3
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: simple-opa
spec:
  version: 0.45.0-stackable0.2.0
  servers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-kafka-opa-rego-kafka
  labels:
    opa.stackable.tech/bundle: "kafka"
data:
  kafka.rego: |
    package kafka.authz

    allow {
        true
    }
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  version: 3.3.1-stackable0.2.0
  zookeeperConfigMapName: simple-kafka-znode
  opa:
    configMapName: simple-opa
    package: kafka/authz
  brokers:
    configOverrides:
      server.properties:
        opa.authorizer.cache.expire.after.seconds: "0"
    roleGroups:
      default:
        replicas: 3
