---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.9.1
  clusterConfig:
    tls:
      internalSecretClass: tls
      serverSecretClass: tls
  controllers:
    roleGroups:
      default:
        replicas: 3
  brokers:
    roleGroups:
      default:
        replicas: 3
