---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-eks
metadata:
  name: kafka-operator-integration-tests
  description: "Cluster for Kafka Operator Integration Tests (AWS EKS)"
publicKeys: []
spec:
  region: "eu-central-1"
  awsInstanceType: "t2.medium"
  versions:
    _-operator: NIGHTLY
    kafka-operator: "$KAFKA_OPERATOR_VERSION"
  node_count: 3
