---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: ionos-k8s
metadata:
  name: kafka-operator-integration-tests
  description: "Cluster for Kafka Operator Integration Tests (IONOS Cloud managed K8s)"
domain: stackable.test
publicKeys: []
spec:
  region: de/fra
  versions:
    _-operator: NIGHTLY
    kafka-operator: "$KAFKA_OPERATOR_VERSION"
  node_count: 3
