---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple-zk
spec:
  image:
    productVersion: 3.8.3
  servers:
    roleGroups:
      default:
        replicas: 3
---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperZnode
metadata:
  name: simple-kafka-znode
spec:
  clusterRef:
    name: simple-zk
---
apiVersion: opa.stackable.tech/v1alpha1
kind: OpaCluster
metadata:
  name: simple-opa
spec:
  image:
    productVersion: 1.0.0
  servers:
    roleGroups:
      default: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-kafka-opa-rego-kafka
  labels:
    opa.stackable.tech/bundle: "kafka"
data:
  kafka.rego: |
    package kafka.authz

    allow if {
        true
    }
---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
spec:
  image:
    productVersion: 3.7.2
  clusterConfig:
    authorization:
      opa:
        configMapName: simple-opa
        package: kafka/authz
    vectorAggregatorConfigMapName: vector-aggregator-discovery
    zookeeperConfigMapName: simple-kafka-znode
  brokers:
    logging:
      enableVectorAgent: true
    configOverrides:
      server.properties:
        opa.authorizer.cache.expire.after.seconds: "10"
    roleGroups:
      default:
        replicas: 3
