= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/kafka-operator/crd/kafkacluster.crd.yaml

To create an Apache Kafka (v3.1.0) cluster named `simple-kafka` assuming that you already have a Zookeeper cluster named `simple-zk`:

    cat <<EOF | kubectl apply -f -
    apiVersion: zookeeper.stackable.tech/v1alpha1
    kind: ZookeeperZnode
    metadata:
      name: simple-kafka-znode
    spec:
      clusterRef:
        name: simple-zk
        namespace: default
    ---
    apiVersion: kafka.stackable.tech/v1alpha1
    kind: KafkaCluster
    metadata:
      name: simple-kafka
    spec:
      version: 3.1.0
      zookeeperConfigMapName: simple-kafka-znode
      brokers:
        roleGroups:
          default:
            replicas: 1
    EOF

If you wish to include integration with https://docs.stackable.tech/opa/index.html[Open Policy Agent] and already have an opa cluster, then you can include an `opaConfigMapName` pointing to the cluster:

    cat <<EOF | kubectl apply -f -
    apiVersion: kafka.stackable.tech/v1alpha1
    kind: KafkaCluster
    metadata:
      name: simple-kafka
    spec:
      version: 3.1.0
      zookeeperConfigMapName: simple-kafka-znode
      opaConfigMapName: simple-opa
      brokers:
        roleGroups:
          default:
            replicas: 1
    EOF

You can change some opa cache properties by overriding:

    cat <<EOF | kubectl apply -f -
    apiVersion: kafka.stackable.tech/v1alpha1
    kind: KafkaCluster
    metadata:
      name: simple-kafka
    spec:
      version: 3.1.0
      zookeeperConfigMapName: simple-kafka-znode
      opaConfigMapName: simple-opa
      configOverrides:
        server.properties:
          opa.authorizer.cache.initial.capacity: "100"
          opa.authorizer.cache.maximum.size: "100"
          opa.authorizer.cache.expire.after.seconds: "60"
      brokers:
        roleGroups:
          default:
            replicas: 1
    EOF

The defaults for `opa.authorizer.cache.initial.capacity`, `opa.authorizer.cache.maximum.size` and `opa.authorizer.cache.expire.after.seconds` are set to `0`.

== Monitoring

The managed Kafka instances are automatically configured to export Prometheus metrics. See
xref:home::monitoring.adoc[] for more details.

== Configuration & Environment Overrides

The cluster definition also supports overriding configuration properties and environment variables, either per role or per role group, where the more specific override (role group) has precedence over the less specific one (role).

IMPORTANT: Overriding certain properties which are set by operator (such as the ports) can interfere with the operator and can lead to problems.

=== Configuration Properties

For a role or role group, at the same level of `config`, you can specify: `configOverrides` for the `server.properties`. For example, if you want to set the `auto.create.topics.enable` to disable automatic topic creation, it can be configured in the `KafkaCluster` resource like so:

[source,yaml]
----
brokers:
  roleGroups:
    default:
      configOverrides:
        server.properties:
          auto.create.topics.enable: "false"
      replicas: 1
----

Just as for the `config`, it is possible to specify this at role level as well:

[source,yaml]
----
brokers:
  configOverrides:
    server.properties:
      auto.create.topics.enable: "false"
  roleGroups:
    default:
      replicas: 1
----

All override property values must be strings.

For a full list of configuration options we refer to the Apache Kafka https://kafka.apache.org/documentation/#configuration[Configuration Reference].

=== Environment Variables

In a similar fashion, environment variables can be (over)written. For example per role group:

[source,yaml]
----
servers:
  roleGroups:
    default:
      envOverrides:
        MY_ENV_VAR: "MY_VALUE"
      replicas: 1
----

or per role:

[source,yaml]
----
servers:
  envOverrides:
    MY_ENV_VAR: "MY_VALUE"
  roleGroups:
    default:
      replicas: 1
----
