= Usage

After installation, the CRD for this operator must be created:

    kubectl apply -f /etc/stackable/kafka-operator/crd/kafkacluster.crd.yaml

To create an Apache Kafka (v2.8.1) cluster named `simple-kafka` assuming that you already have a Zookeeper cluster named `simple-zk`:

    cat <<EOF | kubectl apply -f -
    apiVersion: zookeeper.stackable.tech/v1alpha1
    kind: ZookeeperZnode
    metadata:
      name: simple-kafka-znode
    spec:
      clusterRef:
        name: simple-zk
        namespace: default
    ---
    apiVersion: kafka.stackable.tech/v1alpha1
    kind: KafkaCluster
    metadata:
      name: simple-kafka
    spec:
      version: 2.8.1
      zookeeperConfigMapName: simple-kafka-znode
      brokers:
        roleGroups:
          default:
            replicas: 1
    EOF

If you wish to include integration with https://docs.stackable.tech/opa/index.html[Open Policy Agent] and already have an opa cluster, then you can include an `opa` stanza:

    cat <<EOF | kubectl apply -f -
    apiVersion: kafka.stackable.tech/v1alpha1
    kind: KafkaCluster
    metadata:
      name: simple-kafka
    spec:
      version: 2.8.1
      zookeeperConfigMapName: simple-kafka-znode
      opa:
        configMapName: simple-opacluster
        authorizerClassName: com.bisnode.kafka.authorization.OpaAuthorizer
        authorizerCacheInitialCapacity: 0
        authorizerCacheMaximumSize: 0
        authorizerCacheExpireAfterSeconds: 0
      brokers:
        roleGroups:
          default:
            replicas: 1
    EOF
