apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-kafka-broker-clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
