= Pod placement

You can configure Pod placement for Kafka brokers as described in xref:concepts:pod_placement.adoc[].

By default, the operator configures the following Pod placement constraints:

[source,yaml]
----
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchLabels:
            app.kubernetes.io/component: broker
            app.kubernetes.io/instance: cluster-name
            app.kubernetes.io/name: kafka
        topologyKey: kubernetes.io/hostname
      weight: 70
----

In the example above `cluster-name` is the name of the Kafka custom resource that owns this Pod.

When OPA authorization is configured, Kafka brokers also prefer to run on the same node as the
OPA server Pods. This preferred Pod affinity has weight `50` and uses
`kubernetes.io/hostname` as its topology key. It matches the OPA server Pods by
`app.kubernetes.io/name=opa`, `app.kubernetes.io/instance=<OPA cluster name>`, and
`app.kubernetes.io/component=server`.
The configured OPA discovery ConfigMap is assumed to have the same name as the OpaCluster and
to be in the KafkaCluster's namespace.
This is a scheduling preference, not a guarantee of co-location, and it does not change how
Kafka brokers route requests to the OPA service.
