apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple
spec:
  version:
    kafka_version: 2.8.0
  zookeeperReference:
    namespace: default
    name: simple
  opa:
    reference:
      namespace: default
      name: simple-opacluster
    authorizerClassName: com.bisnode.kafka.authorization.OpaAuthorizer
    authorizerCacheInitialCapacity: 0
    authorizerCacheMaximumSize: 0
    authorizerCacheExpireAfterSeconds: 0
  brokers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: mdesktop
        replicas: 1
        config:
          logDirs: "/tmp/kafka-logs"