apiVersion: kafka.stackable.tech/v1
kind: KafkaCluster
metadata:
  name: simple
spec:
  version:
    kafka_version: 2.8.0
  zookeeperReference:
    namespace: default
    name: simple
  opaReference:
    namespace: default
    name: simple-opacluster
  brokers:
    selectors:
      default:
        selector:
          matchLabels:
            kubernetes.io/hostname: debian
        instances: 1
        instancesPerNode: 1