= Installation
:description: Install Stackable Operator for Apache Kafka using stackablectl or Helm, including dependencies like ZooKeeper and required operators for Kubernetes.

Install the Stackable Operator for Apache Kafka and operators for its dependencies -- ZooKeeper --
as well as the commons, secret and listener operator which are required by all Stackable Operators.

There are multiple ways to install the Stackable Operator for Apache Kafka.
xref:management:stackablectl:index.adoc[] is the preferred way, but Helm is also supported.
OpenShift users may prefer installing the operator from the RedHat Certified Operator catalog using the OpenShift web console.

[tabs]
====
stackablectl::
+
--
The `stackablectl` command line tool is the recommended way to interact with operators and dependencies.
Follow the xref:management:stackablectl:installation.adoc[installation steps] for your platform if you choose to work with `stackablectl`.

After you have installed `stackablectl`, run the following command to install all operators necessary for Kafka:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=stackablectl-install-operators]
----

The tool prints

[source]
include::example$getting_started/install_output.txt[]

TIP: Consult the xref:management:stackablectl:quickstart.adoc[] to learn more about how to use `stackablectl`.
--

Helm::
+
--
Add the Stackable Helm repository:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-add-repo]
----

Then install the Stackable Operators:

[source,bash]
----
include::example$getting_started/getting_started.sh[tag=helm-install-operators]
----

Helm deploys the operators in a Kubernetes Deployment and apply the CRDs for the Apache Kafka service (as well as the CRDs for the required operators).
--
====

== What's next

xref:getting_started/first_steps.adoc[Set up a Kafka cluster] and its dependencies.
