---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple-kafka
  namespace: kraft-migration
spec:
  image:
    productVersion: 3.9.1
    pullPolicy: IfNotPresent
  clusterConfig:
    metadataManager: kraft
    authentication:
      - authenticationClass: kafka-client-auth-tls
    tls:
      internalSecretClass: kafka-internal-tls
      serverSecretClass: tls
    brokerIdPodConfigMapName: broker-ids
  brokers:
    envOverrides:
      KAFKA_CLUSTER_ID: "MyCya7hbTD-Hay8PgCsCYA"
    roleGroups:
      default:
        replicas: 3
    configOverrides:
      broker.properties:
        controller.listener.names: "CONTROLLER"
  controllers:
    roleGroups:
      default:
        replicas: 3
    envOverrides:
      KAFKA_CLUSTER_ID: "MyCya7hbTD-Hay8PgCsCYA"
